
services:
  postgres:
    image: postgres:17
    container_name: pg-notes
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"               
    volumes:
      - notes_pgdata:/var/lib/postgresql/data
      

  adminer:
    image: adminer:4
    container_name: adminer_notes
    restart: unless-stopped
    ports:
      - "8083:8084"


volumes:
  notes_pgdata:
    external: true
